version: "3"
services:
  api:
    container_name: in-gaia-teste-api2-container
    image: node:14
    working_dir: /usr/src/api2
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist:/usr/src/api2/dist/
      - ./package.json:/usr/src/api2/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"